### ISSUE TITLE
Steam: wrong secret

### ISSUE THREAD

**Issue by p1r473** [winauth/winauth#200]
I have made a new Steam account for testing.
When I originally added the authenticator, it showed me a secret and gave me the option to copy this secret, Later, I exported my keys to a text file. However, my secret  and exported OTP AUTH URLs had different secrets. The secret showed originally was 40 characters, whereas the sercet in the exported OTP Auth URL was 32 characters, and they were totally different

**Comment by winauth** [comment]
Are you sure it isn't the same secret? A URl secret is Base32 whereas the one shown in the field for Steam in just hex-encoded.

Put your URI secret in here and check if it's the same as the hex value.

http://tomeko.net/online_tools/base32.php?lang=en

Admittedly I could be showing the Base32 secret instead of the hex code. However, the reason I chose not to was because the Steam authenticator isn't compatible with other platforms like Google Authenticator or Authy, and it could cause confusion.

**Comment by p1r473** [comment]
Okay, you are showing the hexadecimal notation in the first text box and later exporting as Base32. However I'd still recommend showing the Base32 in both places, in case it is ever supported by Authy (I'm emailing them now)

**Comment by p1r473** [comment]
In fact, as you clearly have the best support out of any of the mobile systems (Authy, Authenticator Plus on Android), have you considered making a mobile (Android/iOS port) of WinAuth?

**Comment by winauth** [comment]
I have. Unfortunately this isn't my day-job, and just suffers because of the limited time I can put into it. 

The other mobile apps make it harder to in functionality, since they all do pretty much the same. Especially now I've made available how to add Steam, rest-assured that will be copied and put into other apps.

So maybe. However, the original purpose of WinAuth was because I never had my keyfob and phone to hand when I had to sign in. So maybe a Mac version / Chrome extension would be more suitable first. We'll see.

**Comment by p1r473** [comment]
I had convinced (painstakingly) the people at Authy to support digits=8 a few years ago to get my blizzard authenticator to work with it. However, getting anyone to support anything new is like pulling teeth. To this day, they added digits=8 support to the iOS and Android apps, but never their chrome extension. Also tried getting Authenticar Plus to support digits=8 and its on their to-do list but never got finished.
If you find time one day, a multi-platform WinAuth would be great!
Sorry for off-topic :)

**Comment by p1r473** [comment]
Also, I find the Steam app isnt as safe as using Authy or Authenticator plus where you can encrypt and secure with PINs, etc... whereas the steam app isn't secure.

**Comment by winauth** [comment]
Surprised someone like Authy wouldn't make changes. You would think that's what they would do to make their platform more useful.

I do think about the Android port occasionally, along with a secure sync service. As I say, pure time problem.

Steam are just relying on the rooted aspect of Android. Just like GA. I wasn't surprised to see the secret stored in plain text on my phone. Although I didn't expect to see a formatted URI, given that it's useless elsewhere right now. But it does provide a convenient way to import it into WinAuth (for anyone who is comfortable browsing around under root), so that's a plus!

I'm watching the whole U2F evolution. I think that is more useful. Although they have to make it a whole lot more convenient and available. An example why: I just got an email from some government account I have, insisting it's been 90 days so I need to change my password. Because, why not. Now my post-it is filling up :)

I take it that was your LinkedIn request?

**Comment by p1r473** [comment]
Yea, let's touch base, I am a programmer, maybe I could help implement some features if you're looking for help
I just found the Steam files on my android phone you were talking about, pity that i can't export it into a safer app on Android at this time

**Comment by p1r473** [comment]
Whats the shared secret on the Android steam file?  I recognize the secret as being the Base32 code for 2factor authentication, but there is an additional parameter, shared secret, in a totally different format. Any idea?

**Comment by winauth** [comment]
It's the secret again in Base64.

**Comment by p1r473** [comment]
I deleted the file as it poses some security concern (rogue app trying to grab that file), and it seems that the authenticator still works without it (maybe that file is only needed initially)
its located in /data/data/com.valvesoftware.android.steam.community/files/ for anyone wondering

**Comment by winauth** [comment]
Closing this particular issue. We can pick up other discussions via email.
