### ISSUE TITLE
Regedit Backups defaulted to unknown PGP key

### ISSUE THREAD

**Issue by p1r473** [winauth/winauth#205]
Hello, regarding the regedit backups of WinAuth keys-
Are you decrypting them with your own PGP secret key? Is there any way to make these backups in regedit encrypted with my own PGP keys, rather than the one you are using? I know when I go to export a backup Im offered the chance to encrypt with my PGP public key, does this mean if we do not choose to encrypt with PGP public key, you encrypt it with your own PGP public key by default?
Thanks

**Comment by winauth** [comment]
There is more to it than just what key is being used here.

It would be preferable not to make any backups at all, and leave it down to the user to backup their own keys. However, in reality, they don't do it. If you look back at the history of issues, a high proportion are people with lost passwords/missing or corrupt configs. Without a backup, there is no way for them to recover their authenticators. And remember, these aren't computer or security experts, they are gamers. So this was added to help them out, because they didn't make their own backup.

The PGP key is one that is stored here securely. There is no option to use your own PGP key for the registry backup, because it wouldn't really ever be required. You should be making your own backups, file based or using the Export where you can use a password and your own key.

Currently, there isn't a way to disable the registry backup, it just happens every time a new authenticator is created. However, if you run in portable mode (putting the winauth.xml file in the same folder as the exe) then it gets added in that file and the registry is never touched. This option should probably be added,

**Comment by p1r473** [comment]
I totally understand- perhaps an option to either toggle off registry backups, or, even more prefered, encrypt the registry backups with the same PGP public key we used when we exported our keys.
Slightly offtopic: can you tell me whats a good service or application to generate myself a public and private pgp key pair? I have been playing with OpenKeychain on Android but its a bit confusing. Whats a good way to generate the key pairs that will work well with WinAuth?
Thanks, I will start running in portable mode for now.
(it is just my own paranoia that says encrypting my keys with someone else's public key makes me feel weird... nothing against you :) :) )

**Comment by winauth** [comment]
The issue with using your own key, is having to store and manage it. Just an extra burden, especially in an area that isn't intended to be a replacement for proper backups. Most of the time it can be ignored especially if you manage your own backups.

Not including them is certainly understandable and will be added with an option in the config.

I just use the pgp command line to generate them. However, personally I use [PortablePGP](http://ppgp.sourceforge.net/) for using them, since it is just a lot easier. It can also create new keys.

**Comment by p1r473** [comment]
Thanks. I will probably store them in a secure digital vault.
It just becomes a security concern if one day your PGP keys are ever stolen, and keys are harvested from user's registries (of course this is a doomsday situation, but running in portable mode for me for now is fine)
I will try PortablePGP, thanks!

**Comment by p1r473** [comment]
Though running in portable mode doesn't touch the registry, its still using your keys in the xml file.
What about a feature where we can choose to use our own PGP key globally throughout the app, in the XML backups, the regedit backups, instead of using yours? Or maybe using our own AND yours? And maybe just yours too... options would be nice here! Thanks

**Comment by winauth** [comment]
I will add using your own PGP Key.

**Comment by winauth** [comment]
This is in 3.2.6.

Right now you do it manually by adding the key into the config. Add a new line in the winauth.xml file with your own PGP public key inside a `<pgpkey><![CDATA[ ** key here ** ]]></pgpkey>` tag and the backups will use it instead.

e.g.

```
<?xml version="1.0" encoding="utf-8" standalone="yes"?>
<WinAuth version="3.2">
  <pgpkey><![CDATA[-----BEGIN PGP PUBLIC KEY BLOCK-----
Version: BCPG C# v1.6.1.0

mQENBFWDh3cBCADGIS3vLyS6phDlfWIB8EVGFECKAK3WSPYZ+nl1KDKdfRxcZRNR
NOAhI0XfsKPZr5R/BRC0Yc6Cg0JMbxT4M+YFHT1rlkILoXuDpKhE/+ulnZ43q3sB
N3RkQxOctk3x+AM+I7mK8StMndU+zl8+Oe5IVHDAu7R9AOV4YZk/VS0gxdqzb2O0
dpwYb0/RTGJSiusyqTwq+fHl7el3K0OY4tFWucN0HoIWI8+kgMsjELjO8o4YS0I3
tDfmIiSSNM4hWAtlFoItWco5+3HzJAZJXyPjL7fPuyv6YMmAisa7JXlB4tOdCBaC
8OVf5NbqKffqpN9ZPR9/mxJlrW2/ZpIzTjqzABEBAAG0D2NkbUBsZWdtYWlsLmNv
bYkBHAQQAQIABgUCVYOHdwAKCRD3342ZPEmV3clIB/918NdVlF5SB8Exve5Nbo9E
2ev771TlQ3XXoWbnDflMhuw3RY++tlSn/e2iiaYzFHXHB+Em0qluX8BmEM+DqODm
VQH03Ze7zeHzHEzoVZTPVLtoIuONIoQFwUJHBPwnNF1SA71IPSjBVD8MVen4MagV
3pWCnuLPc+abNqv6odwKseLxWoXJ/co/zE51aNnBzenI3lsNmjILXGsImYtLXEff
Mj8+JA8jyOP6xXzS0zjU9TjrWsA5JyKf1bwGBRnKv3omkTvABsvM5nJelrL67soA
Dst7K7FhNnEwiwVZsNbNHwHNTu3qBPuQZQQHuQZXQczCfNX4bOfmM2KCZS6p4p3E
=DYxW
-----END PGP PUBLIC KEY BLOCK-----]]></pgpkey>
</WinAuth>
```

**Comment by p1r473** [comment]
Hello, you said above that the feature about never adding backups to the registry should be added, but you never added it as a task afaik. This message is just a reminder that you should add that feature (even when not running in portable mode)

**Comment by winauth** [comment]
Backups are only added to the registry if you are not running in portable mode, otherwise they are put into the config file. So I'm not sure which feature you are referring to, as I thought it was all done.

**Comment by p1r473** [comment]
I thought you wanted to add the feature where registry is never touched no matter the mode you're in
Above: "Currently, there isn't a way to disable the registry backup, it just happens every time a new authenticator is created. ... This option should probably be added."

If not, it doesn't matter, I'm running in portable mode myself

I'm testing encrypting it with my personal Public PGP key now. I will post back if I encounter any problems with the decryption portion

**Comment by winauth** [comment]
Reading my comment makes me think I should have had a paragraph break. "This option should probably be added" referring to the PGP key part.

**Comment by p1r473** [comment]
Sure, no problem
So, I have been testing the default PGP key backup in regular mode
Sidenote: doesn't look like you can run portable mode without at least running once in regular mode, as you must run it once (now the registry is touched) in order to generate the winauth.xml. Can you post the binary WITH the XML and package it as "portable version" on the site?
My XML file (in %appdata%: for this test we are NOT using portable mode) is giving an error. What I did was ran WinAuth once to generate the XML file, added my PGP key into that file, then ran WinAuth a 2nd time to add Alice@Google's OTP URL into it. Then, using PortablePGP, I decrypted the message in the registry as winauth.xml and replaced the one in %appdata% with this new decrypted one.
The error I get is:
![image](https://cloud.githubusercontent.com/assets/9235633/9663844/76552434-5234-11e5-9061-f0c3f474d7aa.png)
I can post the decrypted XML file (it's only Alice@Google's keys, so I am okay to post it) if needed. Let me know.

**Comment by p1r473** [comment]
Also of note: once you decrypt the new winauth.xml file, I must re-add my personal public PGP key back to it again. This makes me think yours is hardcoded into the code- which is okay, but what would be better is if my decrypted winauth.xml backup includes my personal PGP public key, in case I forget to re-add it after restoring a backup. So basically when you put the backup into the registry, backup the public key from the XML file into the backup as well, so when restoring it, I don't have to remember to re-add my key to the XML file.

**Comment by winauth** [comment]
The issue is the XML is saved in the wrong encoding, unfortunately the default that .Net decides. I've forced it into UTF-8 so the backup will load without manual adjusting (you can replace UTF-16 with UTF-8).

The PGP won't be added as it is only intended as a minimal backup of the base authenticator data.

**Comment by p1r473** [comment]
What version is the forcing to UTF8 in,  I'll try it out
Thanks

**Comment by winauth** [comment]
I'm fixing it and few other things, so should have a new version today or tomorrow.

**Comment by p1r473** [comment]
3.2.12 seems to have broken being able to use my own PGP key.
I open up WinAuth, then close it. I go to the %appdata% folder, and add my public key into the file. I then open up WinAuth, add an authenticator, then close it. I go into regedit, and copy the value data as the message, and attempt to use the value name as the passphrase. This is the same methodology I used earlier. Though instead of decrypting in the wrong UTF format, I get an entirely different problem altogether:
![image](https://cloud.githubusercontent.com/assets/9235633/9753400/11c356f8-568a-11e5-8cee-9bcb10403a4a.png)

**Comment by p1r473** [comment]
Hi, I followed the same steps as before. However, now, when I decrypt the XML file, and place it into the %appdata% folder, then run WinAuth, WinAuth doesn't read the saved authenticators from it.
As well, going to Add->Import, and importing the decrypted XML file, does not add my authenticator to the GUI.
Something is wrong with it. Why won't the authenticator saved in the XML file show up?
![image](https://cloud.githubusercontent.com/assets/9235633/9753740/04d5b38c-568f-11e5-8373-5c993f3c0669.png)

**Comment by winauth** [comment]
You'll save the data as an xml file, and then use the Add -> Import to add it back in.

**Comment by p1r473** [comment]
Yep, this one is confirmed fixed
