### ISSUE TITLE
kindly create a new password of winauth for me on my registered e mail id rj@y. & i will keep that password saved do it immediately i am in urgent need of it 

### ISSUE THREAD

**Issue by jirochani** [winauth/winauth#207]
kindly create a new password of winauth for me on my registered e mail id rj@y. & i will keep that password saved do it immediately i am in urgent need of it

**Comment by winauth** [comment]
There is no password reset, since your password is used to encrypt your data. All you can do is restore from a backup or from the copies of the secret keys you made when you created each authenticator.

There are backups stored in the registry. From the run command (Win+R), enter "regedit" and on the left side expand each entry down to Computer\HKEY_CURRENT_USER\Software\WinAuth3\Backup. On the right should be multiple entries (other than Default). Double click each one and copy the contents of the Value data field. Put them in a file and send them over to me. winauth@gmail.com

**Comment by jirochani** [comment]
check the attached file i am getting an error kindly help me immediately

**Comment by winauth** [comment]
In that box type "regedit" and click ok. Continue instructions.

**Comment by jirochani** [comment]
-----BEGIN PGP MESSAGE-----Version: BCPG C# v3.1.8.20
hQEMA53DDyNpqwwqAQf/ffHk0TCREHG5O1pBXh9xP7KqAffDsZOxc4kDYgxNGEbCyUQXmYnL2pAEOEQea0RDd8tcMkPNPjOnpMkR6VyyoyUjRh5uNH8jHmHKKedFaZo9EgFLS5V4+VEBPfNBJAf8RVX2v6XaLTQjBcK5BF815H3tBSDQLtlge9+KGvxD/4ROxLZOE0usNhM+Iuc5EyVDT641y0aOjsbhuafxptOYpTf3K2i2CsdIORKg5NfCUpftGe5WAUaBFTrML26WqlVJo6EUIBVmhtS6tFz/xC4ysjjnCkTiNDhtqNOuGGp91As1XkHpVGB6sg2Ysw7NkdbZXxNtdqnT4rn1VUUbQfgAcdLAqgEHOiFwTX5pGqmGJxbqI8Ap9ZVtQvrAfdlRBMV2mD3fSjmhRAkvvAmML637vvzqu8MVsYcnRL1oLYASUOO+nQd+zvGj6tE6HRCyTZSTiNy0CMXB2aeKr1bOKTvudGrtzfouaJiemJwCryoSgaMX90yqrPIUFWiP+3WRhE2HIJeaK26Y2Zm/01zfo1jNkivm13J94cS3kMkZ0j3qPrarfi/w/+hU2jLaNrWFiYvlAUgPDCsrILapg9b6BYJ4YR40Ht7jR1HMMsuSSeUtifa/KFuJtLejljQL6VQVe8joNfv9q6sAJMhsraVyomaNENvVC2DnjnxYEjaYZa/QXUT0Pg+T97zHIJpjH8GR9sn9D6Y9jhX0aytmO5RGNGBS3eWe54ioZu58JaE5K4JkLOMrHpFbnwf/uGaB17npdu7nN5/l0JsPetfUF353yCcOxPt4WM/uo8joyn1kwRhto8DizPWxMWlv6D9kZIIV=+y7U-----END PGP MESSAGE-----

**Comment by winauth** [comment]
You need to email me directly so I can send more instructions on how to restore it. winauth@gmail.com
