### ISSUE TITLE
Forgot password, any way to restore?

### ISSUE THREAD

**Issue by reinhem** [winauth/winauth#214]
As the tittle says I forgot my password.. Is there anyway to restore it?

**Comment by winauth** [comment]
No restore for password since it is used as the key to encrypt your data. However, there is a backup of the authenticators stored in the registry on your computer. From that we can recreate them.

1) Run "Regedit". (press WinKey-R or do Start->run and type 'regedit', click OK).
2) In the left side, click and open up HKEY_CURRENT_USER
3) Click and open Software
4) Click and open WinAuth3
5) Click and open Backup
6) On the right side, you see one or more lines with "---BEGIN PGP MESSAGE---...". Double-click each line to open a window and copy everything in the 'Value data' field.

Email them to me so I can look at it.

**Comment by winauth** [comment]
winauth@gmail.com

**Comment by fandalbante** [comment]
Hi me too have lost the password.
can you help me?
