### ISSUE TITLE
Winauth - Invalid Password after .xml imported to new pc

### ISSUE THREAD

**Issue by dylanmacinnis** [winauth/winauth#221]
Recently, I moved and was unable to bring my desktop pc with me. Fortunately, I did take my ssd and 3 hdd's and was able to recover my .xml for winauth. Although, when I imported it over to my laptop, I instantly was given a invalid password message and using my own password did not resolve anything.

I still have access to my old os on my ssd, are there any other files that I could transfer over to fix this problem?

Thanks in advance,
Dylan

**Comment by winauth** [comment]
Sounds like you had the "encrypt to be only useable on this computer" option on. If so, the data has been encrypted with your old Windows account master key.

If you are able to run Windows from the old drives, you need to go in and turn this off before you copy the xml file over. Otherwise, you would need to first recover the old master key (from a Windows password restore disk) and set up a new account on your laptop with that key.

If you can't do that, see if you can access the registry from the old installation so you can pull out the backups.

**Comment by dylanmacinnis** [comment]
Unfortunately, the laptop I am using is a significant downgrade. My hardware is probably worth 70$-200$ in contrast to my 1000$ pc I built, with that said, I was unable to install my SDD to this laptop. I would like to try and boot off my ssd, but I haven't been able to change the boot order off this pc yet. Like, is it even possible to boot off of a HDD dock?

Also, how do I access the backups of the registry(if possible at all) by entering my HDD's through the laptop?

How would go about with accessing the registry

**Comment by winauth** [comment]
If you can connect the old drive using a USB->SATA/IDE cable, you could use VirtualBox and set up a virtual Windows Machine that uses that drive to boot.

Or, to access the backups from the registry, you can use regedit to open the old ntuser.dat file from your old Windows user folder.

**Comment by dylanmacinnis** [comment]
I'm looking into VirtualBox now, I'll get back to you asap.

**Comment by dylanmacinnis** [comment]
I'm rather confused about the Virtualbox software. The SSD is currently in my hard-drive dock and connected to my laptop via USB, the SSD is running on my E: drive... ..Would I follow a tutorial like this?

http://www.howtogeek.com/187721/how-to-boot-from-a-usb-drive-in-virtualbox/

**Comment by winauth** [comment]
Yes, that looks right. Obviously creating a Windows image. Since you are using the raw disk, you need to be very careful you don't overwrite it.

I would perhaps suggest you try and access the old registry first. Find ntuser.dat from your old user folder and open it up in regedit. Then expand HKCU\Software\WinAuth3\Backup and grab each entry. Those are backups and we can recreate the authenticators.

**Comment by dylanmacinnis** [comment]
Where exactly do I go in order to find that file? I went to F:\Windows and didn't know where to go from there.

**Comment by dylanmacinnis** [comment]
I got it to work, although, this laptop cannot support 64 bit and the computer was 64 bit.

**Comment by winauth** [comment]
<root-drive>\Users\<your-username>

**Comment by dylanmacinnis** [comment]
As in F:\Users\<my-username>? No files are present here.

**Comment by winauth** [comment]
You mean there is nothing in Users or nothing in \Users\<username> ?

If the folder exists, the files might be hidden because of permissions. Right click the <username> folder, into the Security tab, and give yourself access.

**Comment by winauth** [comment]
Let's move this to email. winauth@gmail.com
