### ISSUE TITLE
"Enter code in current window..." problem

### ISSUE THREAD

**Issue by thbemme** [winauth/winauth#228]
If you set a shortcut for "Enter code in current windows or one called" it doesn't paste into the SWTOR Launcher. Pasting the code into any other edit box works.

![launcher](https://cloud.githubusercontent.com/assets/14074615/10117020/d4223920-6450-11e5-92db-4ea26fa8dab0.jpg)

**Comment by winauth** [comment]
Yep. It uses a keyboard emulation, which is probably going to the wrong window, since it looks like it is a frame with a browser window inside.

I'll try and find a fix.

**Comment by winauth** [comment]
After further investigation, the reason here is that the SWTOR launcher is running in elevated privilege mode - why you get a Yes/No confirmation before it opens. You would have to run WinAuth at the same level, i.e. right click and "Run as Administrator", and then it works.

Not sure if this can be fixed.

**Comment by thbemme** [comment]
This workaround fixed the problem. Thanks. Are there any security
implication while using WinAuth in admin mode?

**Comment by winauth** [comment]
You wouldn't normally give admin rights to an application that you didn't trust, as it just gives that app access to otherwise protected files. It's odd that SWTOR is asking for it by default. I can understand when it wants to update, but it could request it just for that.

WinAuth will work fine, as long as you are happy giving it right. You might want to change the shortcut itself to set it permanently as "run as admin" rather than having to right click each time.

Personally, I have just gotten used to using the shortcut key to "copy" the code and then paste into the SWTOR window.

**Comment by winauth** [comment]
Can't really solve as just requires raising privilege. I've been using a shortcut key to copy and then just doing a manual paste.
