### ISSUE TITLE
a device attached to your service is not functioning.

### ISSUE THREAD

**Issue by nyuusuki** [winauth/winauth#231]
I don't know when winauth stopped working for me but when I did a deep clean to get rid of LavasoftTCPservice.dll, which was stopping me from doing quite a few things. it stopped working. Maybe it was connected to that file in some manner? Either way it wasn't something that was good for my system, but now I can't run my winauth, I've seen someone previously had this issue but installing the newest version of .network didn't help my case.

**Comment by winauth** [comment]
It sounds like the error is because your network adapter is messed up. WinAuth will check if there is network connectivity then check for a latest version and sync the time of any out of date authenticators. Just trying to access the network is broken.

Are you getting other network issues?

I would probably see if you can go into your Device Manager and see if you can remove the network adapters, then do "FInd New Hardware" and have Windows add them again. This might reset any missing files.

**Comment by nyuusuki** [comment]
What if it doesn't replace what's gone and I removed them?

**Comment by nyuusuki** [comment]
I managed to fix it without reseting everything, had to use netsh winsock reset which replaced the files lavasoft killed on me.

**Comment by winauth** [comment]
Great.
