### ISSUE TITLE
Countdown for visibility of a code does not align with validity of a code

### ISSUE THREAD

**Issue by berlincount** [winauth/winauth#239]
One is forced (i.e. it's non-optional) to un-hide the desired code(s), which shows a countdown clock.

This countdown clock counts down until the code is hidden again, which might be before or considerably after the code expires. If the code expires its display isn't updated.

I'd prefer making hiding the code optional, and better alignment with existing userinterface concepts in other apps, i.e. showing a clockwise countdown for the code validity instead of a count-clockwise countdown for the code visibility.

If code hiding is enabled I'd like the code to be visible during its whole validity span, and hidden afterwards. In border cases (like the code being valid less than 3s or so), the countdown clock should be RED, the code should stay visible & be updated on screen after it expired, and then the regular countdown clock should be shown together with the code until it expires.

Thanks for this awesome piece of software :)

**Comment by BakuDM** [comment]
That would be cool, it's pretty hard to enter high number codes, you need to memorize it, because if you Alt-Tab in to enter half of the number and then Alt-Tab out to see the rest of it, it's gone.

Also, it's not about the thread but I don't want to create one just to ask it, the "Always on top" feature only works with Windowed or Windowed Fullscreen, right? Because at least for me, when I open Wildstar (Fullscreen) it take the focus on the screen and WinAuth doesn't get on top of it.
And sometimes even with "Always on top" enabled it doesn't work properly, it doesn't even get on top of Chrome, but I need to investigade more when it happen before report it.

**Comment by winauth** [comment]
Thanks for the suggestions. I can see that it would be nice to have the full 30 sec countdown as well as being able to hide the code.

The current countdown display is 10 seconds, since it is long enough to see and remember the code, without having it visible for too long. It also shouldn't normally matter if the 10 seconds goes over a 30 sec window into the next code, since the spec for HOTP is that the server accepts a drift of one or two codes. I'll be interested to hear if you have an example where it fails.

Of course, having the the current code shown and hidden when it expires could mean you only see if for 1/2 sec and then it's gone, but then, as you say, you are just showing it anyway, which is what is happening now. It all becomes about timing.

Because of this, most implementations seem to either display the current code for a short while or just always display the codes. Do you have an example of one that shows the current one then disappears?

You can always right click and "copy" instead, which I personally end up doing a lot, or set up the action to copy for you.

@BakuDM Always on top is just using Windows own flag. It probably won't be on top of a full-screen window, but should be on top of Chrome. Or is it  in full-screen app mode? Fee free to create a new issue so I can look into it.

**Comment by BakuDM** [comment]
@winauth Sadly the "copy" doesn't work with Wildstar, because you need to click in the numbers on the screen instead of type it. :C 
But it works with the others app thought.

Like I said, I don't know exacly how and when it happen, I don't know if it only happen in the first time I open it after powering my PC or if it's random, I need to investigate more.
