### ISSUE TITLE
[Steam] Auto-confirmation does not work

### ISSUE THREAD

**Issue by Kein** [winauth/winauth#309]
I set the period to 1 minute and set action to "Auto-Confirm"

32 minuets and one dinner later still nothing.

**Version:** 3.4.19

**Comment by winauth** [comment]
Right-click and do Confirmations. Do you have to login?

**Comment by Kein** [comment]
Nope, I'm logged in alright just fine. Manually every time I open the window with confirmations it is there but no auto-confirm for any.

**Comment by winauth** [comment]
Can you run winauth with logging. You need to add "--log debug" at the end. i.e. right-click the icon, Properties, put --log debug after winauth.exe

Start winauth and do what you did before. It will create a log file called winauth.log, in either the same folder or in c:\Users\<username>\AppData\Roaming\WinAuth. Can you email it to me.

**Comment by winauth** [comment]
To winauth@gmail.com

**Comment by Kein** [comment]
I'm a little bit paranoid to share even the log but I figured out the issue. When I log in just with "Remember me" option it never auto-confirms eve if it does not ask me to login in every time. But when I log in with "Remember me" + "Permanently" it does auto-confirmations except the thing is: app fails to remember me permanently. I never has this issue in Android Emu with  emulated app. Is there a way to fix it in WA?

**Comment by winauth** [comment]
"Remember" was supposed to remember your Steam session till you restarted WinAuth. "Permanently" also saves it in your config, so it continues to work across restarts. However, it may be that without "Permanently" some session data is being lost and so auto-confs fail.

In the next version I've only have the "remember" option, since it always saves permanently. You obviously can't do auto-confs with remembering your details, and then it shouldn't even give the option.

There is still a bug where it forgets you at some point, that I'm trying to narrow down.

**Comment by winauth** [comment]
Hopefully fixed this in 3.4.22

**Comment by Kein** [comment]
How do I back up the data before applying it? Don't want to get locked if something goes wrong.

**Comment by winauth** [comment]
Use the Options button (cog icon) and do Export, into a password-protected file.

**Comment by Kein** [comment]
Updated. Nice, it didn't even ask for a password when I entered "Confirmations" window.
