### ISSUE TITLE
I CANT ACCEPT TRADES IN STEAM. AUTHENTICATOR. HELP:(

### ISSUE THREAD

**Issue by betchiepotchi** [winauth/winauth#324]
When i confirming trades, it says in winauth confirmation, "Trade can not be confirmed."  why is that?? pls helppp :(

**Comment by winauth** [comment]
Can you run winauth with logging. You need to add "-l debug" at the end. i.e. right-click the icon, Properties, put "-l debug" after winauth.exe.

Do it again and it'll create a log file \Users\<username>\AppData\Roaming\WinAuth\winauth.log

**Comment by betchiepotchi** [comment]
then what should i do?

**Comment by winauth** [comment]
Send it to me. winauth@gmail.com

**Comment by betchiepotchi** [comment]
wait 1 last question. is changing Trade url is a factor of restriction in trading? because i changed it a while ago, don't know if it is the reason.

**Comment by winauth** [comment]
Don't understand your question. Are you talking about family mode?

**Comment by betchiepotchi** [comment]
I mean, my trading URL, my main trading URL in steam, the one im using for trade offers. Im just asking if this is the reason why i cant trade.. because im using winauth for many months now, and i can run it smoothly, then i changed my trading URL and it suddenly is not working. Sorry for bad english and disturbance xD

**Comment by winauth** [comment]
Well, it could be a coincidence, but I don't know if that's the problem. The log file should show the error somewhere near the end when you tried to confirm. Hopefully it'll shed some light on the problem.

**Comment by betchiepotchi** [comment]
ok i sent it :)

**Comment by winauth** [comment]
Thanks. Got it.

There is an error in there, "It looks like there is a problem with the time or timezone settings on your device. You will not be able to act on any confirmations until that problem is resolved.".

This probably means that the time on your computer is different from Steam. Stop WinAuth. Make sure the clock in Windows is correct, and that it is set to the correct timezone. Best to let Windows auto-update the time. You can do that click the clock in the right and going into Date and Time Settings.

Once it looks right, open WinAuth and right-click your Steam authenticator and choose "Sync Time".

Try your trade again.

**Comment by betchiepotchi** [comment]
lol that actually works!!.. haha i feel so stupid. thank you very much winauth :) i got so scared i thought i got banned or something. :) thank you again!. btw your app is so amazing and i love using it. yay!

**Comment by winauth** [comment]
No problem. I'm sure you wouldn't have guessed that was the problem, I didn't.

Glad you like it!
