### ISSUE TITLE
WinAuth password issue when trying to login on a second user

### ISSUE THREAD

**Issue by Kevk96** [winauth/winauth#331]
hi, i have the problem that my main win user acc is broken and have to use a local user now. when i try to use winauth it always says invalid password... i can still use it on the broken account but it takes long to switch to it. is there a way to use winauth on my second user too?

**Comment by winauth** [comment]
Sounds like you've got password security in WinAuth that's encrypting it to that user. Go back to the broken account, open WinAuth, click the option icon and "Choose Protection..." and untick the "And only be the current user on this computer". Should then work with any user.

Otherwise, you can use the "Export.." to create a password-protected backup (you should do this anyway) and then use Add in a new version on WinAuth.

**Comment by Kevk96** [comment]
i´ve found my problem... i made a 1/1 copy of my broken win user and also copied the winauth files.. i had to delete the xml in appdata to get it working :D anyway thx its working now

**Comment by winauth** [comment]
Ok.
