### ISSUE TITLE
Invalid password when I import xml authenicator file

### ISSUE THREAD

**Issue by kathxox15** [winauth/winauth#348]
I'm importing the winauth.xml file and it says invalid password every time. I did reinstall windows completely so I'm hoping that isn't the cause of the issue. However I did save the xml file on an external drive before reinstalling so I'm able to send the xml file / password.

thanks!

**Comment by winauth** [comment]
Did you have "Encrypt to only be useable on this computer" turned on?

![winauthprotection](https://cloud.githubusercontent.com/assets/12179488/15377102/1944945a-1d0e-11e6-9cd7-cbc0bcc76f66.png)

If so, then it has been encrypted by your previous Windows installation. You need to restore Windows or use the Windows password reset disk to access you old account.

If you can't do this, you can restore WinAuth if you made any backups, if you made any.

You can re-create the authenticators from the secret codes you wrote down, if you did.

You can restore from a saved copy of the Windows registry from your last installation, if you have it.

Otherwise, there is no way to recover the data. You need to contact the services you use 2FA and have them remove it.

**Comment by kathxox15** [comment]
Hi,

Yes I had it to Encrypted to my computer only.


"You can re-create the authenticators from the secret codes you wrote down, if you did."

Do you know how I can do this step? I do remember some codes that the Authenicator gave me if that helps

**Comment by winauth** [comment]
The secret keys you had to type in to add each one. They are long strings looking like WIUH8747J75H6H. If you have those, you can just re-enter them.

If you used Steam, you can use the Recovery code to remove it from your account.

**Comment by kathxox15** [comment]
Oh I thought you meant the 6 digit pins you get every time you log into the game. I don't believe I got the the string pin that you mentioned. I'll try and check my registry files
