### ISSUE TITLE
Steam "incorrect login" if password has some special characters?

### ISSUE THREAD

**Issue by Ephrael** [winauth/winauth#368]
Hi Colin,
the password of my steam account had some special characters (i.e. **£**, **(** and **"** ); I tried to add the account to WinAuth but it said "incorrect login". After removing those special characters from the password, WinAuth was able to add the aforementioned account without that error message.
Maybe there's a problem with special characters?
I just wanted to let you know...

Thanks,
Eph

**Comment by winauth** [comment]
Thanks, wasn't aware of that. I'll look into it.

**Comment by winauth** [comment]
Steam doesn't actually save special characters in the password, they get stripped out. Try it yourself. Log into the website and just don't type them as you type your password, you'll still get logged in fine.

**Comment by Ephrael** [comment]
Thanks for your answer Colin,
but I've just tried to not type all the special characters of the password of my _secondary_ account...it does not login (both steam client and steam website). The string you mentioned says "non-ascii chars" but I think they are all ascii chars (according to Wikipedia "ascii punctuation and symbols").
I'm a bit confused :(

**Comment by winauth** [comment]
Maybe just terminology between special characters and punctuation. Normal punctuation should be fine, e..g ( ) { } !, however, you included a pound sign £, which would be classed as a special character.

If you create a password with a £ in it, you'll find it's completely ignored, i.e. what I meant when I said you can type your password and just ignore it.

The is the same for any keys above 127 in this [ASCII table](http://www.asciitable.com/). Essentially, usernames and passwords are limited from 32 "Space" to 126 "~".

Since £ is 156, it gets ignored.

This is just how Steam works.

Nonetheless, I've fixed WinAuth to clear out special characters (like £) as they were causing the "invalid login" error. It'll be in the next release.

**Comment by Ephrael** [comment]
Ah, now I understand! Thanks for the clarification...
Many thanks also for your time and dedication: without WinAuth I'd be lost, considering I only have a Windows Phone (no official authenticator for us).

**Comment by winauth** [comment]
No problem.
