### ISSUE TITLE
WinAuth PGP Key

### ISSUE THREAD

**Issue by FlyingFroggy** [winauth/winauth#413]
Hello, so I have my WinAuth PGP key because my WinAuth crashed and no longer opens can you please help me by sending me my stuff, I failed to make a backup because I never thought anything happened but I was wrong. Please help <3 

-----BEGIN PGP MESSAGE-----
Version: BCPG C# v3.5.1.2

hQEMA53DDyNpqwwqAQf/ZPgyQJUaOGrpzaYXpKEPk/Nir8EiCua1jkFyJ/JsG8A7
qpG6qc7dxtbXps996n4aTfGfZdvlakHoJbXrpGGrY+C0m6KWn4Bw+FDGxcP2npRS
OQVKlqxFPfTT+MjIdAVWbFoIbR3/ktXY+d2rLEG6jt1r8Qp37AiLEoEUYX5JeV7F
E+I9fWUP7CmCcSdUod7v6R/mNoo/et3WgBfq54lC1ySsFSjUFuFdLXAAMKa3IW8C
X/ByI23ZuknEQ5weWOWvZwQdLQunIgkEYvDx00ovT6K5klJyXmdq5s3sWrKYHDIy
J1iyRUTOcE8lTfLi94aAwrH0Dk9Pfkt1SJXngnanStLCnwHulkBgntcd/gWQfFfG
yyF9CF5KFwhc+c9OSEGeyUDz79PWsMkndEYSy92YwmkvMUnuddJZqnc+GC7xUnJX
ys1A9D8LnJQY5sOHcj4G4m8owCqrIT7DTu38xMliAthHSnZKCzKbcPNVTHaItXpZ
5iFBi+KbkpWRxzEFXtqoe19kWzVKRRCAOG8gVblVWmFXoJoDYFGo1SfxX4zELi39
r7oZBITuC1l5TbFdkJ/zaa3r2Zd/Z2O4a4jEOLLTk3DTS4WqezVz2ymz5Ald8R0w
ipsaebxBVNPonbFwNltp34xvIdLFp1sW47Vo70h5QTvF7ArDGKREBpI21DiMLXVk
Gucm5FzEvcXg2d0inAcGiVEmTQ4nZDhujkckYcXrDCQe7d4JtF0rSXDDai44Y4OB
1C37ZrA4HCZME0MvjU21hXDLquUE0mZ2IrysStKOaeQ/vRjZDxkYyYXMII4Th74D
9J6IiiZkuk/7NY3DesXwsldESrJBhXqe+FgneZhvjkhGA5ac6wDaC5tibzy9JAyP
NtCiwJXB+DpdOK6abyt0KKd7+Ml7et2PPUdPyjucPlD1YZLj928WaEGRYT07NGGX
T4q9wv12DHiVGjU80sey3N5LAnZwmLYLhCqQOS3zsnifYZBooKbioTNSEwLyCYlQ
YcYBBaR2/tPmiNymiknOeT7XHRhI6F/xi7bJG89yi9yaE0BDJWGhd4akAZBErGnn
TlTA/r4hGSwp6G50qmGG1iAmvY66Db9yVdZaCIIRdeLLsvl6KTON3kA2EvqqFanl
lbCRYPzVvOTx+WPREfKkDIES1zvlhV287HBY6zAqWM2r1C9h+XWRC1AvnvjaxCiw
4sqFPlhtb6iVMw5Ios/FcqmwIDVD8L/yYa49leJ9Tu1GHlhoDpaH7k7Vx7IJ1GhC
wWaFb1KBJ31rc4ouJAA3UelqtyvGGmau/BfzLfVLhkfaZziVoWutnrBl51uq82Ya
1/HFAOnhEnkbaDC3r/HhMBPBk4S9GwR1vpFBP7bhY1r+LK7++7+/DublvAbdDk/A
0NFj2j9l0plJssiHelXc3w7Xkk4YswWeknNIwZZ0WqWH2J0qFcwJHDa70chCMMK1
5Wp7Zs+zS7dZw+V3N8gId84Lis0Yb+tr+aTvojcpd/tx
=tR3D
-----END PGP MESSAGE-----

and

-----BEGIN PGP MESSAGE-----
Version: BCPG C# v3.5.1.2

hQEMA53DDyNpqwwqAQgAjM9uFE5dIcZK+k/NndeCsmXlIBT2yIbOVgBsX8aVhsXx
p6uRDmx1W+5fitoYBjuLUeyXkdtlXyXRk17Xsa2oCpoSmwA5oxESZbYvbPlSEGR+
Dt2Ywx1/2FQyYaW59r8TfwntxtSOy42doc45EsQMQnbv0laJXVSsSSF4DMCPpmCE
4niZHmrhm86dBbry3hAHfJPkJ5PUXHl3EOloPBEBPBnMzssSJ1IhDF/tDxbd8jng
h6/kX5QBUau5ky0E6/XaP34eVbmRH4WHv42+c/aLV7W08oQEaYyxgg1JRx0km2Xf
VbYAABgIQpYldEk5VfJSe75UDVDCsPCLdRBn6rjVbNLCogFpGMVQJ3p0GcZT+aln
fvDBU7G32W7U/R9cUFHTzoOCbO2+7J/sIng+WbQ0QyWoXCDrDqt/YjYsretArLWN
pWStdpWZdV5xdGW9kk40GloyBdtUCTM8gQnDOxj39EHyFbiwaWzQWqJvXw9q5mSl
uwRMffdz3VdncXgHvTOGc1h8mt95go7znJ+QN9d9trBIPHM9bWyEegVRWuP/q7kl
g2ZH2WDhr2AvEBZn3+yI+/LiFiePQDlorgLAcQzZRn6ah2Sx96K4ab9DZ1JEwbjJ
YwVLb7m5zUdx7+eDsG4XEJz6Y8yhPKAsnBmg8X5KsxElbHF7TBcYCGLdDrebVOkH
qoQFjSbv+F9Q8u58ADND30KqCZgRBPYAV6qG8PFojGctwp7Z5Jfr3pg5jNAu6KOw
2t8OrcIPaoRn3OpG2cpYbDPIwnXL2KIJWzLM3RfB/3PKsCmEnenoSthiKxsu+t0s
romTFHxWNo0bcpBq8ZNOS9H3nvXda6NIFpQ8hp7iYoWXsToHKjpHXkJv8HiPZZnX
f2d/uIQrAyjqSI5uMZCYKzIdvPqVaLUIlqeEy4n+rU8J/CiZCoJyeVEuCxGf8VmP
l1KJF41mYHukzJrzbq+I9+goSpUNznLT8QPZUc/HuxoGll1rVYcw4KR8CO37xgYN
rK67RycWHu0hLJAfJRuwYwdCHnm1AcSxoz7mlkydLMNW6W98IyogPJMIkI3n5+Uu
C+J/qz7sakY7cFtR12QO339vkJZfW4OF83Po623c6VDDX6lGPTS0nu7TyjwBwEvn
FiYz5W2ZSzPiR/jPlRwldZ9JBlko5lQ6OaHVG1us7TxgPnVwubCHB5E4+hKz9LXT
QocmlnfN/AnKwTvZoxuH+ny+ohI9g5jKESLcOtQU8LljuSe5FUeQyDfBv6g1C+3A
CvRrKnAVYm9BIcEqrslmTGlTubJdIFpJT3DYpwsb66p73fbiNTwqHNxDsAIevgBd
lZmEjTZ3+buupi2QTW+DyDLS5vKklHqdSEI5D0za+bsVgwJd7biDynfjJtKIu4c5
/G7EhunxnIqm0y/lqsvjBl6ALUSu2KJl7UsW8knIALDHHGEf+Dhxlg3e9vZ7n4zT
pBdPFyTe2qzfis31BLpGmaIU42A05IGnNDNWV5+TUpmyZuVy
=BiDH
-----END PGP MESSAGE-----

**Comment by winauth** [comment]
What's your email?

**Comment by FlyingFroggy** [comment]
flyingfaglol@gmail.com (not a fake email really my email xDD )

**Comment by winauth** [comment]
Just sent it to you.

**Comment by FlyingFroggy** [comment]
Thank you.

**Comment by winauth** [comment]
No problem...make that backup :)

**Comment by entis47** [comment]
I happen to have the same problem, My xml just cleared itself, probably because of windows defender, and I do not have any backups, is it possible to recover my "stuff"?

here are the pgp keys.

-----BEGIN PGP MESSAGE-----
Version: BCPG C# v3.5.1.2

hQEMA53DDyNpqwwqAQgAl1Oy5WKn3yWLHnGjCxcqs/KjjNjYzjYjz2V9z6E8GtQA
zV9IQgcr5UL3wPygPELElRuzV+H+260DwuWVJfSVdnnntgTH7zgEhzB+U0s6Mskd
mHpD03r0rpPPe5ZFUoAHUZTGOup5otgMZ29xJ/qtUI/dbCmy38wGnPw4Wnuh8KnE
/mhg8wRp9Fz6Dk0VoWyjR2xlZTfWW7gefZ2CTQUcwSy2aB6s/4gBhge87H42mLgM
TrJm0Fd8A8rSY/grvPIV6VqM80V74X3884LwWCJ+fDVAqcSyl2KQiURTlI5Cy6Ca
aPseuucmhHgpJdetQE2JXuWXhQ90zwJaB9oG+7Ke+9LCjgHx8b88sgMZrUyImWsY
+nvarmmzJTEsuTyCA6/B4UTZu5naSurTDxIqF1ngsEQM2gGbVQw9kwQjFpP1kEMw
JMVFYbj2Vl881llQLNM56UcOeEizKNxzFOJ5FjN/ZLJz1bTmjlbUbDeL49Sa8Rv0
8fg8e/Cl4483RBivcdSWvx7OnrJQ0HJgFtu1to7nKS62heyAxbhzvTVNaNApO5c1
8spey0MgwXFgHsjq6mSCp24Cpfx189FXFFdClzJzm+jVBnJpkZRDzIQDeX57kCr+
aU3rS+VkuSSFvpEsFOntLrK597XNqj5c6WQjGlHIEy0cYzuFrArrwOMqrV9S6VLk
9wSWPQbPqyQotgARINpKX7Cbka+RODYZcBwXmEGXFzHwZehOu1G1FWJUFUrrLCOa
RH7798mn4KqnUULuKk1uhAYK6VmU8ek+kJU/tvW+WNx+RBC8kOmo+LFqHNCF9/pb
yBBbmCR0cyWc5JcvmstzJNVnkna+C++sRMu2bfFjYXtcfOGjdJA4oupz77EEv0Dw
AXk5Gwkv8ycpkdMY8g7VvjSRUOe9iWZPQ8cDJXdb+G2OAaQ6tFzzR+CwJ1BtgEhJ
PlEzJITMpWutGUJk6rYDVauVu7PgsI85kV4Z1ZaEXJy7/ei3o8GC2DJTHyUfNcWf
ES9CnFrcm/kmcD1gSLt0lOKCulMqaUOfYkrqySWCVWrmw7sdTzCZ3XGKp4C7WX+r
7tTnua4WJE6BK7YEnpo8iTjhovbzJhWbJ0oEcmmY/JzSLjJR1AtDwqgqPUn52XxT
ADQmgq8AVLHDQ6L/cgHzx+0C2UY4HeYF4L0MksV+mKkUabBlnuga7hgC00Plwk0P
IJjk0vUKfwynQyfj7eDj7M4DO3cPY6UxHxlhAkDF/lKyByD7uH+p4GDUOVTXD2Mo
4qUjUZ6fvFtGK7NCgbJwbbk3nr+HJnk0ooVvShE6586pdjiDbr/EANJiRF9dAt9h
2ehe1xqZVr2tYWB9njfmIMfgVhsI0hDL4+BJRAnOdaxycUcF0WYb1Ios2OzikzlF
8fe/i0nhKjxqs1cyL3P3bMs4FDJO898c3wIl8n1W4VzViA5mHOr8xWCtSb1NlTqa
7+8QgkkNXrt5IaLdO0jmlA==
=giwa
-----END PGP MESSAGE-----


and 

-----BEGIN PGP MESSAGE-----
Version: BCPG C# v3.5.1.2

hQEMA53DDyNpqwwqAQf/QUc68a+EvOdU0v4yX1HHcOjSoAgvyPf/odAtPaDQ8sMj
9yGPvK/Qd9rsnx71w21wu++UHFE9jrzX4ASLcDt5x9NF6Dip1JWCnVteqy7KxsH/
XOJii3uWmhNcgbcN9l378lp4EvxgzeQUR6LpBew9Rb2/O0y6L4GBJKuO+SZxPDnf
FymKXI76PQkTq2Ncm4iRWd1fbSyNZ6jjz2tbRIYFNrL2ItWz4G+2w21tHh+BYfKO
LqVOtfqxa1Cve3McbNtnJPMGG9ldjQKLm44+HXgCjyhxV3zrL+iWLSVtw12gv84X
ob2Il9ZeclRcb/t2Jdgz60aR96F0OY9sWAIm0Us3h9LArgFh6aqTG3QL9nyc8Pqk
qwfoio+ZK6isyqCEH17YBCYh9pbOPq0LsjyMHR2gWzLGGvUXQOoWLmx+zgSkA/7r
vKeU4SwbX+L+p8ImGXvj8dzupz7J3YAx/izaSCtD6s/iccv5QrDWM0QaHi1FaejP
9qFDAtEhyeB0C6zjhGiVpmVNOm9CkQ6ZbvUxVEHHPL/qtOSa2EWv9iqpSqBNumGj
lRmbAza8xDFnG8QYpBlp0N2Kl+YpUTYeV0kRcivz3iaSCXdwYpXwjIQusUnMLx9t
tRgg6bFQQT2VTdDcjrOuy+TB7E1Ms4rm2Wh+xykKcg0+lle2AbEfI2JbIMQ3rRtn
teAmLJFvUkhUfrDFIm4cZyzg/dRbNlwvvFo++2XB+c8XfImPVEqqL4ALvnvmiq7x
MUw6457387ASBLoS9GhfAff6cT15wyzTPNffVx0TO8poUIFE6EEMzAlrimzGyrGL
antouHF3kDFQcNk86YqPQQ==
=Yx6b
-----END PGP MESSAGE-----


and 

-----BEGIN PGP MESSAGE-----
Version: BCPG C# v3.5.1.2

hQEMA53DDyNpqwwqAQf/ffEM63KsO/xXsRrhpR3v0OoEi0iVQaF9UK8+NbLDR4Cr
8BOhRppbdL7454+AILkjvE/ufUu6MY7sdy2xZT4ER5poOFLj7K/rMMRq6e7Gvggg
cSkNPIOgWo0XkeAcTwJBGoxC4iczYGZOEYlIMFUJlfRBYEIKyfvgjOLG0+n+ig73
/PtUP/62TqDuTHi/61F440BjVn2lO7Sr8W8N3ZtbkYMDxf/CyeY2awCXtCyowmkn
fPD7UYbEqz3KO4ClKwcNKXbDVn5ActPC0UxKP5+9v+v3a2LBS0YXEt/y/axZZuOl
3ry6pIJScwexoqlZ50FS4xChOMSj2h2x0ts97KP9Z9LCoAGx2JAUNjybfqYzryMd
PDU6M57OiBAVtz0R3snM2+3pjOyg6YjnLIivlntqMLxEPs2BUvXwp322ujfOUwJs
LBHWaEnLtHPKqYyUicykpE4gvRya7iMER3++7NDjbBnYH6wlaO6La6Nd+0uXzvQA
vn1XnQiyMXGieDL0kvy9vcSyJZfEezayuW0PomSRJ4HQzulAV14tnnVvrxx1buXt
41fbx7OHH2Aa9e15VFR+bmnlufqVu4KRpvzGgae5o3kgtI404i1V7QLS54nTaL63
ugECXAbe56GGNbPZi0tE99FVxrTte95ox/Juax6V4kE8/OOAcf2Rec88nwvohGt/
/S61SnnElX493x5Bs7tW/D4lD5+n/c5Ddl4ze5Xd/jRGfVfDvijk0Pea9578IO/3
5uwXYp2/MeI3/9m/G/7QWv3/97y9hLspppjjs7ipUYJVcaI/vwOoAAuNMXGvj25P
XkkzqIqYagOn/dKbd7f6MWDcNVkyyNHSDcJt4+FG/avDbRMqbjYtMjeAexeDKiC6
sMlmy4Pxi6uHA3YUOLhOLJBBIrKS8J2sXkDidKuKlUx0c/c6DBdLJ/b7FP7/fFiq
cODjTbKtORIXrdHz4qwBhsMCdCHb2miBMPFY8LV9E5Bh+qK3CXo+T+/rwe0AEVcj
RcEueI4LeGXBiOt4GrcKiqrdI/rGxaOixcLMgTXV6QWI1KGOYx1e3+HGWmoXKm2E
gtkOWIEkQWRqfguOx+TBJRUqXIq7s60MWrdQXua7uCzNZeV4pslJputY5c8ehPtY
tMNRVf9wXPtkFKFKhD3JTIQmHDPQVfvzLu4ZreJIR75ocXLE9t6JR0fDEVcBElse
2W3D2ksaZJHOBS1f3hrxndyiyBn9QdhgfOOBBgRU9CpZV0faBx/DupdxcnKUIW3A
JR3VA2TMz7tUVO5EVMbWE5czwGmItCDpn189Yh32oxabZSp56YqcM9zhCegftqWZ
q7PSOObL1orynI7Hlu/GyNw/zCDJ4xlxje5hFfVAFUSNEG5qAvzOIwMkiYhYFkip
uYQMH7UjNBbjGIK6YufCBoCA0i6nXkK+0hqQfAjmlZnGLqmX/kVqEZ68DRZDGjQu
GrqRrAkrp+BTPfw0MDTj9EiBKhpAHLrT9Afq9V4/+R4rEg==
=jR9B
-----END PGP MESSAGE-----
