### ISSUE TITLE
hexadecimal error 0x00 is an invalid character line 1, position 1 (Windows 10)

### ISSUE THREAD

**Issue by Nellblade** [winauth/winauth#512]
So winauth was working just fine until yesterday, today when I boot my pc and try to login to winauth I get this error. I have no idea what went wrong, any help would be deeply appreciated (I have no backup of the xml file).

**Comment by winauth** [comment]
Can you follow the instructions at the bottom of https://winauth.com/lost-forgotten-password/ and email the file to me at winauth@gmail.com

**Comment by kratsa** [comment]
Hello. I have the same issue and i have shared secret and backup code. How can i fix this with those?

**Comment by winauth** [comment]
See above and send email to me and winauth@gmail.com

**Comment by pandymic** [comment]
I'd just like to comment that I began experiencing the same problem following a hard power-off. I'm convinced that Windows applied some system patches during the reboot, but can't be sure. Poring over the system event logs now, in case it helps.

**Comment by pandymic** [comment]
No entries in any of the Windows Logs around the time I tried running the application for the first time after startup, unfortunately. Just the typical "System did not shut down correctly" flavor text from the system.

Are you thinking this is an issue with the PGP signatures?

**Comment by pandymic** [comment]
I've just done some more troubleshooting. I had initially glassed over my %APPDATA%/WinAuth/winauth.xml file and assumed all was OK because the system was reporting 40KB filesize.

I just opened it up and, it turns out, it's filled with 40KB of NUL character. 40,911 instances of NUL then EOF. I suspect it became corrupted during the hard-reboot?

**Comment by winauth** [comment]
Yes, I think this is just due to failures while we are updating the file. The file gets overwritten with a load of zeros. As far as I've found, it's due to disk write-caching when the power fails. Basically the file is not actually updated on disk.

**Comment by pandymic** [comment]
Thanks for the follow-up. I'll restore from backup.

I'm guessing there's metadata (like HOTP counter) that must be continually written to the XML file so loading to memory on boot and leaving the file alone isn't really an option.

**Comment by winauth** [comment]
The config file includes not just the authenticator data but also program settings: window size, flags, etc.

The authenticators will trigger an update if, as you say, the counter changes, but also if the time sync gets updated - should only be once a day, renaming or reordering.

The file also gets updated if it's resized, or one of the options is changed.

One of the problems, I think, is that the update is delayed so multiple changes can be batched. Ironically, this was put it to avoid chances of corrupting the file (from the same issue).

The file is also re-created, meaning Windows is allocating a new space on disk. If a power failure happens before the write-caching has updated then you end up with a file of zeros.

**Comment by winauth** [comment]
I think something to help here would be to write the changes to a temporary file, rename the old file as a ".bak", then rename the new file.

This way if there is a failure we'll still have the old file, either as it was or as a .bak file.

**Comment by pandymic** [comment]
Would there be any benefit to breaking the configuration into multiple files, similar to how FileZilla does it? One of the saving graces was that while my general program settings were lost when "filezilla.xml" corrupted, my site manager data was spared as it is saved to a separate "sitemanager.xml" file which is spared because the file is only written when specific changes are made.

Similarly, base authenticator data could be saved separately from more frequently written metadata, like time sync and counters. Now, while losing HOTP counter data can be problematic, TOTP time-sync data could be easily rebuilt.

UI data could be handled separately from authenticator data. Window size and position information isn't mission critical and losing it doesn't really impact day-to-day use. It's superfluous really, so it could stand to be handled separately from the meat-and-potatoes stuff.

**Comment by winauth** [comment]
Yes, it may have even been like that once . The reason it isn't now is really portability, so you could have a single file with all the data.

While this definitely would help, because less writes, it doesn't completely stop the problem from happening. 

If this really is the cause, it would be good to try and mitigate the circumstances.

**Comment by pandymic** [comment]
I can certainly see the benefits of trying to keep the package tidy for portability, similar to how Notepad++ or KeyPass offer a USB flash-drive install, but in those cases data is stored locally in one folder.

In the case of WinAuth where items are being written to the user's local AppData space as well as the system registry that concept seems to go a bit to the wayside anyway.

At the end of the day onus is definitely on the user to maintain regular backups, because there's no guarantee against data loss under any circumstances, a vast majority of which are definitely out of the developers hands anyway.

I would push, however, for a separation of configuration values specific to authenticator data from those that have to do with UI/UX. Perhaps those can be offloaded onto the system registry, since they're specific to the specific user session or desktop environment anyway.

**Comment by halamadridbero** [comment]
hello, i have same problem, can i fix it ?

**Comment by deke997** [comment]
@winauth I just started having the same problem after a power failure. I didn't have an xml backup, but I do have the PGP messages from the registry. What do I do with them?

**Comment by winauth** [comment]
@deke997 email it to me winauth@gmail.com
