### ISSUE TITLE
Does WinAuth use internet time?

### ISSUE THREAD

**Issue by ingber** [winauth/winauth#575]
We've been using WinAuth for quite some time time now and it works just fine.  We also have Authy installed.

Today, I noticed Authy was giving incorrect codes, which I traced back to my PC losing ~30 secs.  WinAuth was still giving correct codes for our logins.  I sync'd the PC OK, and Authy is now correct and agrees with WinAuth.

If my PC clock was off, how did WinAuth keep generating correct codes?  Does WinAuth actually use an internet server for its time?

**Comment by winauth** [comment]
Yes, when we added the Google authenticator implementation, their recommended approach was to query www.google.com and take the time from the response header. This is done on startup to calculate any drift between your computer and the "internet". Since most are based on that implementation, they use the same time.
